### PR TITLE
Support for lodash 4

### PR DESCRIPTION
**Pull request by rposborne**
contains has been replaced with includes in lodash ^4

### CODE REVIEW

**Comment by mohsen1** [comment]
Thanks for the PR! You need to update lodash dependency in `package.json` as well.

**Comment by rposborne** [comment]
@mohsen1 Just didn't want to make that call for you.  Also happy to drop support :).

**Comment by mohsen1** [comment]
If we can get rid of Lodash dependency it would be amazing! Most of those functions are now in JavaScript!

**Comment by rposborne** [comment]
@mohsen1 Think dropping lodash might be a bit much.  At first pass of removal, I have had to reimplement half of these methods.

**Comment by mohsen1** [comment]
ok that's fine. If tests pass I'll merge and publish this

**Comment by rposborne** [comment]
@mohsen1 Actually might need help, the fail is in npm (if installed with yarn) all tests pass.  But I can't figure out what is going wrong when I install with npm.   It seems as such that mocha is not getting the correct version of lodash.

**Comment by dzikoysk** [comment]
obraz

**Comment by rposborne** [comment]
@mohsen1 any chance we can get this merged?

**Pull request merged**
