### PR TITLE
WIP: Refactor to use yaml-unist-parser  AST

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by cajurabi** [comment]
Moshen, just an FYI, prettier uses yaml-unist-parser for its Yaml AST, and yaml-unist-parser uses yaml/parseAST to creates its AST.  Looking at the root project: https://eemeli.org/yaml/#yaml, it seems like it may be a good idea to use it as the AST parser.  Reading the docs (which are thorough) shows that it has a YamlDocument object which retains the comments and exposes a method to create nodes to insert, along with a toString method to generate the YAML.  Lastly, it allows you direct access to its AST, and provides a way to parse a modified AST into a Yaml.Document format which provides YAML validation and the ability to stringify to YAML, etc.

**Comment by mohsen1** [comment]
You are right. Using the prettier printer will screw up the formatting. We should make our own printer that does minimal damage to the original YAML.

**Comment by mohsen1** [comment]
@cajurabi adding that AST parser to AST Explorer would be an amazing help:

https://github.com/fkling/astexplorer

Example PR to look at: https://github.com/fkling/astexplorer/pull/182

**Comment by cajurabi** [comment]
@mohsen1 sounds fun.  I have been playing with the AST from YAML.  🤮  The yaml-unist-parser has a good basis for transforming the AST into different structure.  I'm assuming that AST Explorer requires the AST in a standard format, or at least helper classes to walk it.  I'll look into it.  My recommendation is not to reinvent the wheel as the Yaml package has a lot of really good work put into it.  I'll let you know how my testing goes.

**Comment by mohsen1** [comment]
@cajurabi FYI https://github.com/fkling/astexplorer/pull/329

**Comment by eemeli** [comment]
The low-level mostly-internal `yaml` AST is indeed rather horrible as a UI to build on, esp. as it doesn't account for a rather large chunk of the YAML syntax checks. It's really only meant to be a slightly nicer building block than the raw string contents.

What additions would you need for the [YAML.Document](https://eemeli.org/yaml/#yaml-document) structure to work as an AST for your puposes?

**Comment by cajurabi** [comment]
@eemeli great work on the YAML package.  I’m about 95% done with a YAWN like editor—was fairly straightforward once I figured out the AST structure with the help of your excellent documentation.  BTW, there is a bug in handling comments in a multiline flow sequence, where a null value can be inserted.  I will try to track down and fix.  Also I noticed merges don’t work correct as well so I will look into. As for the AST I wish there was a standard industry-wise.  I personally would prefer a more simplistic tree with node property consistentency.  However, once I understood how the YAML package AST was organized it made perfect sense to the how and why it was implemented that way.  Don’t change a thing please.

**Comment by mohsen1** [comment]
@cajurabi are you working on a branch off this repo? I'm eager to see your progress and consolidate efforts. I don't find enough time to take this change list to the finish line

**Comment by eemeli** [comment]
@cajurabi As a heads-up, the `rc.4` release of `yaml` renames the lowest-level API more appropriately as a CST rather than AST parser, and its `YAML.Document` level API  is now more clearly defined and documented as a proper AST: https://eemeli.org/yaml/#ast-nodes

**Pull request closed without merging**
